//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Presentacion.cl.ssichilexpress.ws {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DireccionesSSOSOAP", Namespace="http://www.chilexpress.cl/DireccionesSSO/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(anyNode))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(datosConsumidor))]
    public partial class DireccionesSSO : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private datosHeaderRequest headerRequestField;
        
        private datosHeaderResponse headerResponseField;
        
        private System.Threading.SendOrPostCallback ValidarDireccionOpOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultarRegionesOpOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultarOficinasOpOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultarComunaCoberturaOpOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public DireccionesSSO() {
            this.Url = global::Presentacion.Properties.Settings.Default.Presentacion_cl_ssichilexpress_ws_DireccionesSSO;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public datosHeaderRequest headerRequest {
            get {
                return this.headerRequestField;
            }
            set {
                this.headerRequestField = value;
            }
        }
        
        public datosHeaderResponse headerResponse {
            get {
                return this.headerResponseField;
            }
            set {
                this.headerResponseField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ValidarDireccionOpCompletedEventHandler ValidarDireccionOpCompleted;
        
        /// <remarks/>
        public event ConsultarRegionesOpCompletedEventHandler ConsultarRegionesOpCompleted;
        
        /// <remarks/>
        public event ConsultarOficinasOpCompletedEventHandler ConsultarOficinasOpCompleted;
        
        /// <remarks/>
        public event ConsultarComunaCoberturaOpCompletedEventHandler ConsultarComunaCoberturaOpCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("headerRequest")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("headerResponse", Direction=System.Web.Services.Protocols.SoapHeaderDirection.Out)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ValidarDireccionResponse", Namespace="http://www.chilexpress.cl/DireccionesSSO/")]
        public ValidarDireccionResponse ValidarDireccionOp([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.chilexpress.cl/DireccionesSSO/")] ValidarDireccionRequest ValidarDireccionRequest) {
            object[] results = this.Invoke("ValidarDireccionOp", new object[] {
                        ValidarDireccionRequest});
            return ((ValidarDireccionResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ValidarDireccionOpAsync(ValidarDireccionRequest ValidarDireccionRequest) {
            this.ValidarDireccionOpAsync(ValidarDireccionRequest, null);
        }
        
        /// <remarks/>
        public void ValidarDireccionOpAsync(ValidarDireccionRequest ValidarDireccionRequest, object userState) {
            if ((this.ValidarDireccionOpOperationCompleted == null)) {
                this.ValidarDireccionOpOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidarDireccionOpOperationCompleted);
            }
            this.InvokeAsync("ValidarDireccionOp", new object[] {
                        ValidarDireccionRequest}, this.ValidarDireccionOpOperationCompleted, userState);
        }
        
        private void OnValidarDireccionOpOperationCompleted(object arg) {
            if ((this.ValidarDireccionOpCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidarDireccionOpCompleted(this, new ValidarDireccionOpCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("headerRequest")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("headerResponse", Direction=System.Web.Services.Protocols.SoapHeaderDirection.Out)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ConsultarRegionesResponse", Namespace="http://www.chilexpress.cl/DireccionesSSO/")]
        public ConsultarRegionesResponse ConsultarRegionesOp([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.chilexpress.cl/DireccionesSSO/")] ConsultarRegionesRequest ConsultarRegionesRequest) {
            object[] results = this.Invoke("ConsultarRegionesOp", new object[] {
                        ConsultarRegionesRequest});
            return ((ConsultarRegionesResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarRegionesOpAsync(ConsultarRegionesRequest ConsultarRegionesRequest) {
            this.ConsultarRegionesOpAsync(ConsultarRegionesRequest, null);
        }
        
        /// <remarks/>
        public void ConsultarRegionesOpAsync(ConsultarRegionesRequest ConsultarRegionesRequest, object userState) {
            if ((this.ConsultarRegionesOpOperationCompleted == null)) {
                this.ConsultarRegionesOpOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarRegionesOpOperationCompleted);
            }
            this.InvokeAsync("ConsultarRegionesOp", new object[] {
                        ConsultarRegionesRequest}, this.ConsultarRegionesOpOperationCompleted, userState);
        }
        
        private void OnConsultarRegionesOpOperationCompleted(object arg) {
            if ((this.ConsultarRegionesOpCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarRegionesOpCompleted(this, new ConsultarRegionesOpCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("headerRequest")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("headerResponse", Direction=System.Web.Services.Protocols.SoapHeaderDirection.Out)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ConsultarOficinasResponse", Namespace="http://www.chilexpress.cl/DireccionesSSO/")]
        public ConsultarOficinasResponse ConsultarOficinasOp([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.chilexpress.cl/DireccionesSSO/")] ConsultarOficinasRequest ConsultarOficinasRequest) {
            object[] results = this.Invoke("ConsultarOficinasOp", new object[] {
                        ConsultarOficinasRequest});
            return ((ConsultarOficinasResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarOficinasOpAsync(ConsultarOficinasRequest ConsultarOficinasRequest) {
            this.ConsultarOficinasOpAsync(ConsultarOficinasRequest, null);
        }
        
        /// <remarks/>
        public void ConsultarOficinasOpAsync(ConsultarOficinasRequest ConsultarOficinasRequest, object userState) {
            if ((this.ConsultarOficinasOpOperationCompleted == null)) {
                this.ConsultarOficinasOpOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarOficinasOpOperationCompleted);
            }
            this.InvokeAsync("ConsultarOficinasOp", new object[] {
                        ConsultarOficinasRequest}, this.ConsultarOficinasOpOperationCompleted, userState);
        }
        
        private void OnConsultarOficinasOpOperationCompleted(object arg) {
            if ((this.ConsultarOficinasOpCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarOficinasOpCompleted(this, new ConsultarOficinasOpCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("headerRequest")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("headerResponse", Direction=System.Web.Services.Protocols.SoapHeaderDirection.Out)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ConsultarComunaCoberturaResponse", Namespace="http://www.chilexpress.cl/DireccionesSSO/")]
        public ConsultarComunaCoberturaResponse ConsultarComunaCoberturaOp([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.chilexpress.cl/DireccionesSSO/")] ConsultarComunaCoberturaRequest ConsultarComunaCoberturaRequest) {
            object[] results = this.Invoke("ConsultarComunaCoberturaOp", new object[] {
                        ConsultarComunaCoberturaRequest});
            return ((ConsultarComunaCoberturaResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarComunaCoberturaOpAsync(ConsultarComunaCoberturaRequest ConsultarComunaCoberturaRequest) {
            this.ConsultarComunaCoberturaOpAsync(ConsultarComunaCoberturaRequest, null);
        }
        
        /// <remarks/>
        public void ConsultarComunaCoberturaOpAsync(ConsultarComunaCoberturaRequest ConsultarComunaCoberturaRequest, object userState) {
            if ((this.ConsultarComunaCoberturaOpOperationCompleted == null)) {
                this.ConsultarComunaCoberturaOpOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarComunaCoberturaOpOperationCompleted);
            }
            this.InvokeAsync("ConsultarComunaCoberturaOp", new object[] {
                        ConsultarComunaCoberturaRequest}, this.ConsultarComunaCoberturaOpOperationCompleted, userState);
        }
        
        private void OnConsultarComunaCoberturaOpOperationCompleted(object arg) {
            if ((this.ConsultarComunaCoberturaOpCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarComunaCoberturaOpCompleted(this, new ConsultarComunaCoberturaOpCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.chilexpress.cl/OSB/EBO/HeaderRequest")]
    [System.Xml.Serialization.XmlRootAttribute("headerRequest", Namespace="http://www.chilexpress.cl/DireccionesSSO/", IsNullable=false)]
    public partial class datosHeaderRequest : System.Web.Services.Protocols.SoapHeader {
        
        private datosTransaccion transaccionField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public datosTransaccion transaccion {
            get {
                return this.transaccionField;
            }
            set {
                this.transaccionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.chilexpress.cl/OSB/EBO/HeaderRequest")]
    public partial class datosTransaccion {
        
        private string fechaHoraField;
        
        private string idTransaccionNegocioField;
        
        private string idTransaccionOSBField;
        
        private string sistemaField;
        
        private string usuarioField;
        
        private string oficinaCajaField;
        
        private datosTransaccionNodoHeader nodoHeaderField;
        
        /// <remarks/>
        public string fechaHora {
            get {
                return this.fechaHoraField;
            }
            set {
                this.fechaHoraField = value;
            }
        }
        
        /// <remarks/>
        public string idTransaccionNegocio {
            get {
                return this.idTransaccionNegocioField;
            }
            set {
                this.idTransaccionNegocioField = value;
            }
        }
        
        /// <remarks/>
        public string idTransaccionOSB {
            get {
                return this.idTransaccionOSBField;
            }
            set {
                this.idTransaccionOSBField = value;
            }
        }
        
        /// <remarks/>
        public string sistema {
            get {
                return this.sistemaField;
            }
            set {
                this.sistemaField = value;
            }
        }
        
        /// <remarks/>
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
            }
        }
        
        /// <remarks/>
        public string oficinaCaja {
            get {
                return this.oficinaCajaField;
            }
            set {
                this.oficinaCajaField = value;
            }
        }
        
        /// <remarks/>
        public datosTransaccionNodoHeader nodoHeader {
            get {
                return this.nodoHeaderField;
            }
            set {
                this.nodoHeaderField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.chilexpress.cl/OSB/EBO/HeaderRequest")]
    public partial class datosTransaccionNodoHeader : anyNode {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.chilexpress.cl/OSB/EBO/HeaderRequest")]
    public partial class anyNode {
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.chilexpress.cl/OSB/INTERNO/IMP/ConsultarRegionesResp")]
    public partial class RegionType {
        
        private string codRegionField;
        
        private string glsNombreField;
        
        /// <remarks/>
        public string codRegion {
            get {
                return this.codRegionField;
            }
            set {
                this.codRegionField = value;
            }
        }
        
        /// <remarks/>
        public string glsNombre {
            get {
                return this.glsNombreField;
            }
            set {
                this.glsNombreField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.chilexpress.cl/OSB/INTERNO/IMP/ConsultarRegionesResp")]
    public partial class ConsultarRegionesResponseType {
        
        private EstadoOperacionType estadoOperacionField;
        
        private RegionType[] listaRegionesField;
        
        /// <remarks/>
        public EstadoOperacionType estadoOperacion {
            get {
                return this.estadoOperacionField;
            }
            set {
                this.estadoOperacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("region", IsNullable=false)]
        public RegionType[] listaRegiones {
            get {
                return this.listaRegionesField;
            }
            set {
                this.listaRegionesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.chilexpress.cl/OSB/EBO/EstadoOperacion")]
    public partial class EstadoOperacionType {
        
        private string codigoEstadoField;
        
        private string descripcionEstadoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string codigoEstado {
            get {
                return this.codigoEstadoField;
            }
            set {
                this.codigoEstadoField = value;
            }
        }
        
        /// <remarks/>
        public string descripcionEstado {
            get {
                return this.descripcionEstadoField;
            }
            set {
                this.descripcionEstadoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.chilexpress.cl/OSB/INTERNO/IMP/ConsultarComunaCoberturaResp")]
    public partial class ComunaCoberturaType {
        
        private System.Nullable<int> codErrorField;
        
        private bool codErrorFieldSpecified;
        
        private string glsErrorField;
        
        private System.Nullable<int> codOficinaField;
        
        private bool codOficinaFieldSpecified;
        
        private string glsCoberturaField;
        
        private string glsComunaField;
        
        private string glsSectorField;
        
        private System.Nullable<decimal> idProvinciaField;
        
        private bool idProvinciaFieldSpecified;
        
        private string idRegionField;
        
        private System.Nullable<decimal> idCentroUrbanoField;
        
        private bool idCentroUrbanoFieldSpecified;
        
        private System.Nullable<decimal> codigoIneField;
        
        private bool codigoIneFieldSpecified;
        
        private System.Nullable<decimal> idComunaField;
        
        private bool idComunaFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> codError {
            get {
                return this.codErrorField;
            }
            set {
                this.codErrorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codErrorSpecified {
            get {
                return this.codErrorFieldSpecified;
            }
            set {
                this.codErrorFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string glsError {
            get {
                return this.glsErrorField;
            }
            set {
                this.glsErrorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> codOficina {
            get {
                return this.codOficinaField;
            }
            set {
                this.codOficinaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codOficinaSpecified {
            get {
                return this.codOficinaFieldSpecified;
            }
            set {
                this.codOficinaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string glsCobertura {
            get {
                return this.glsCoberturaField;
            }
            set {
                this.glsCoberturaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string glsComuna {
            get {
                return this.glsComunaField;
            }
            set {
                this.glsComunaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string glsSector {
            get {
                return this.glsSectorField;
            }
            set {
                this.glsSectorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> idProvincia {
            get {
                return this.idProvinciaField;
            }
            set {
                this.idProvinciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idProvinciaSpecified {
            get {
                return this.idProvinciaFieldSpecified;
            }
            set {
                this.idProvinciaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string idRegion {
            get {
                return this.idRegionField;
            }
            set {
                this.idRegionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> idCentroUrbano {
            get {
                return this.idCentroUrbanoField;
            }
            set {
                this.idCentroUrbanoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idCentroUrbanoSpecified {
            get {
                return this.idCentroUrbanoFieldSpecified;
            }
            set {
                this.idCentroUrbanoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> codigoIne {
            get {
                return this.codigoIneField;
            }
            set {
                this.codigoIneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoIneSpecified {
            get {
                return this.codigoIneFieldSpecified;
            }
            set {
                this.codigoIneFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> idComuna {
            get {
                return this.idComunaField;
            }
            set {
                this.idComunaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idComunaSpecified {
            get {
                return this.idComunaFieldSpecified;
            }
            set {
                this.idComunaFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.chilexpress.cl/OSB/INTERNO/IMP/ConsultarComunaCoberturaResp")]
    public partial class ConsultarComunaCoberturaResponseType {
        
        private EstadoOperacionType estadoOperacionField;
        
        private ComunaCoberturaType[] listaComunaCoberturaField;
        
        /// <remarks/>
        public EstadoOperacionType estadoOperacion {
            get {
                return this.estadoOperacionField;
            }
            set {
                this.estadoOperacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("comunaCobertura", IsNullable=false)]
        public ComunaCoberturaType[] listaComunaCobertura {
            get {
                return this.listaComunaCoberturaField;
            }
            set {
                this.listaComunaCoberturaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.chilexpress.cl/OSB/INTERNO/IMP/ConsultarComunaCoberturaReq")]
    public partial class ConsultarComunaCoberturaRequestType {
        
        private string regionField;
        
        private System.Nullable<int> tipoCoberturaField;
        
        private System.Nullable<int> usoCoberturaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string region {
            get {
                return this.regionField;
            }
            set {
                this.regionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> tipoCobertura {
            get {
                return this.tipoCoberturaField;
            }
            set {
                this.tipoCoberturaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> usoCobertura {
            get {
                return this.usoCoberturaField;
            }
            set {
                this.usoCoberturaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.chilexpress.cl/OSB/INTERNO/IMP/ConsultarRegionesReq")]
    public partial class ConsultarRegionesRequestType {
        
        private int codZonaField;
        
        /// <remarks/>
        public int codZona {
            get {
                return this.codZonaField;
            }
            set {
                this.codZonaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.chilexpress.cl/OSB/INTERNO/IMP/ConsultarOficinasResp")]
    public partial class OficinaType {
        
        private string idNombreCalleField;
        
        private string glsOficinaField;
        
        private int numeracionField;
        
        private string numCaracterAntField;
        
        private string numCaracterPostField;
        
        private string codComunaIneField;
        
        private decimal numBlockField;
        
        private decimal numDireccionField;
        
        private decimal valLatitudField;
        
        private decimal valLongitudField;
        
        private string glsCalleField;
        
        private string glsComunaField;
        
        private string codComunaField;
        
        private string glsAliasField;
        
        /// <remarks/>
        public string idNombreCalle {
            get {
                return this.idNombreCalleField;
            }
            set {
                this.idNombreCalleField = value;
            }
        }
        
        /// <remarks/>
        public string glsOficina {
            get {
                return this.glsOficinaField;
            }
            set {
                this.glsOficinaField = value;
            }
        }
        
        /// <remarks/>
        public int numeracion {
            get {
                return this.numeracionField;
            }
            set {
                this.numeracionField = value;
            }
        }
        
        /// <remarks/>
        public string numCaracterAnt {
            get {
                return this.numCaracterAntField;
            }
            set {
                this.numCaracterAntField = value;
            }
        }
        
        /// <remarks/>
        public string numCaracterPost {
            get {
                return this.numCaracterPostField;
            }
            set {
                this.numCaracterPostField = value;
            }
        }
        
        /// <remarks/>
        public string codComunaIne {
            get {
                return this.codComunaIneField;
            }
            set {
                this.codComunaIneField = value;
            }
        }
        
        /// <remarks/>
        public decimal numBlock {
            get {
                return this.numBlockField;
            }
            set {
                this.numBlockField = value;
            }
        }
        
        /// <remarks/>
        public decimal numDireccion {
            get {
                return this.numDireccionField;
            }
            set {
                this.numDireccionField = value;
            }
        }
        
        /// <remarks/>
        public decimal valLatitud {
            get {
                return this.valLatitudField;
            }
            set {
                this.valLatitudField = value;
            }
        }
        
        /// <remarks/>
        public decimal valLongitud {
            get {
                return this.valLongitudField;
            }
            set {
                this.valLongitudField = value;
            }
        }
        
        /// <remarks/>
        public string glsCalle {
            get {
                return this.glsCalleField;
            }
            set {
                this.glsCalleField = value;
            }
        }
        
        /// <remarks/>
        public string glsComuna {
            get {
                return this.glsComunaField;
            }
            set {
                this.glsComunaField = value;
            }
        }
        
        /// <remarks/>
        public string codComuna {
            get {
                return this.codComunaField;
            }
            set {
                this.codComunaField = value;
            }
        }
        
        /// <remarks/>
        public string glsAlias {
            get {
                return this.glsAliasField;
            }
            set {
                this.glsAliasField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.chilexpress.cl/OSB/INTERNO/IMP/ConsultarOficinasResp")]
    public partial class ConsultarOficinasResponseType {
        
        private EstadoOperacionType estadoOperacionField;
        
        private OficinaType[] listaOficinasField;
        
        /// <remarks/>
        public EstadoOperacionType estadoOperacion {
            get {
                return this.estadoOperacionField;
            }
            set {
                this.estadoOperacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("oficina", IsNullable=false)]
        public OficinaType[] listaOficinas {
            get {
                return this.listaOficinasField;
            }
            set {
                this.listaOficinasField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.chilexpress.cl/OSB/INTERNO/IMP/ConsultarOficinasReq")]
    public partial class ConsultarOficinasRequestType {
        
        private string codRegionField;
        
        private decimal codOficinaField;
        
        private bool codOficinaFieldSpecified;
        
        /// <remarks/>
        public string codRegion {
            get {
                return this.codRegionField;
            }
            set {
                this.codRegionField = value;
            }
        }
        
        /// <remarks/>
        public decimal codOficina {
            get {
                return this.codOficinaField;
            }
            set {
                this.codOficinaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codOficinaSpecified {
            get {
                return this.codOficinaFieldSpecified;
            }
            set {
                this.codOficinaFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.chilexpress.cl/OSB/INTERNO/IMP/ValidarDireccionReq")]
    public partial class ValidarDireccionRequestType {
        
        private string glsDireccionField;
        
        /// <remarks/>
        public string glsDireccion {
            get {
                return this.glsDireccionField;
            }
            set {
                this.glsDireccionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.chilexpress.cl/OSB/INTERNO/IMP/ValidarDireccionResp")]
    public partial class DireccionType {
        
        private int codResultadoField;
        
        private string glsResultadoField;
        
        private string nombreCalleField;
        
        private string numCaracterAntField;
        
        private string numeracionField;
        
        private string numCaracterPostField;
        
        private string complementoField;
        
        private string codRegionField;
        
        private string glsRegionField;
        
        private string glsComunaField;
        
        private string codComunaField;
        
        private decimal numBlockField;
        
        private decimal numDireccionField;
        
        private decimal numSegmentoField;
        
        private decimal valLatitudField;
        
        private decimal valLongitudField;
        
        /// <remarks/>
        public int codResultado {
            get {
                return this.codResultadoField;
            }
            set {
                this.codResultadoField = value;
            }
        }
        
        /// <remarks/>
        public string glsResultado {
            get {
                return this.glsResultadoField;
            }
            set {
                this.glsResultadoField = value;
            }
        }
        
        /// <remarks/>
        public string nombreCalle {
            get {
                return this.nombreCalleField;
            }
            set {
                this.nombreCalleField = value;
            }
        }
        
        /// <remarks/>
        public string numCaracterAnt {
            get {
                return this.numCaracterAntField;
            }
            set {
                this.numCaracterAntField = value;
            }
        }
        
        /// <remarks/>
        public string numeracion {
            get {
                return this.numeracionField;
            }
            set {
                this.numeracionField = value;
            }
        }
        
        /// <remarks/>
        public string numCaracterPost {
            get {
                return this.numCaracterPostField;
            }
            set {
                this.numCaracterPostField = value;
            }
        }
        
        /// <remarks/>
        public string complemento {
            get {
                return this.complementoField;
            }
            set {
                this.complementoField = value;
            }
        }
        
        /// <remarks/>
        public string codRegion {
            get {
                return this.codRegionField;
            }
            set {
                this.codRegionField = value;
            }
        }
        
        /// <remarks/>
        public string glsRegion {
            get {
                return this.glsRegionField;
            }
            set {
                this.glsRegionField = value;
            }
        }
        
        /// <remarks/>
        public string glsComuna {
            get {
                return this.glsComunaField;
            }
            set {
                this.glsComunaField = value;
            }
        }
        
        /// <remarks/>
        public string codComuna {
            get {
                return this.codComunaField;
            }
            set {
                this.codComunaField = value;
            }
        }
        
        /// <remarks/>
        public decimal numBlock {
            get {
                return this.numBlockField;
            }
            set {
                this.numBlockField = value;
            }
        }
        
        /// <remarks/>
        public decimal numDireccion {
            get {
                return this.numDireccionField;
            }
            set {
                this.numDireccionField = value;
            }
        }
        
        /// <remarks/>
        public decimal numSegmento {
            get {
                return this.numSegmentoField;
            }
            set {
                this.numSegmentoField = value;
            }
        }
        
        /// <remarks/>
        public decimal valLatitud {
            get {
                return this.valLatitudField;
            }
            set {
                this.valLatitudField = value;
            }
        }
        
        /// <remarks/>
        public decimal valLongitud {
            get {
                return this.valLongitudField;
            }
            set {
                this.valLongitudField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.chilexpress.cl/OSB/INTERNO/IMP/ValidarDireccionResp")]
    public partial class ValidarDireccionResponseType {
        
        private EstadoOperacionType estadoOperacionField;
        
        private DireccionType[] listaDireccionesField;
        
        /// <remarks/>
        public EstadoOperacionType estadoOperacion {
            get {
                return this.estadoOperacionField;
            }
            set {
                this.estadoOperacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("direccion", IsNullable=false)]
        public DireccionType[] listaDirecciones {
            get {
                return this.listaDireccionesField;
            }
            set {
                this.listaDireccionesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="datosTransaccion", Namespace="http://ws.chilexpress.cl/OSB/EBO/HeaderResponse")]
    public partial class datosTransaccion1 {
        
        private string internalCodeField;
        
        private string idTransaccionNegocioField;
        
        private System.Nullable<System.DateTime> fechaHoraInicioTrxField;
        
        private System.Nullable<System.DateTime> fechaHoraFinTrxField;
        
        private string estadoField;
        
        /// <remarks/>
        public string internalCode {
            get {
                return this.internalCodeField;
            }
            set {
                this.internalCodeField = value;
            }
        }
        
        /// <remarks/>
        public string idTransaccionNegocio {
            get {
                return this.idTransaccionNegocioField;
            }
            set {
                this.idTransaccionNegocioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> fechaHoraInicioTrx {
            get {
                return this.fechaHoraInicioTrxField;
            }
            set {
                this.fechaHoraInicioTrxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> fechaHoraFinTrx {
            get {
                return this.fechaHoraFinTrxField;
            }
            set {
                this.fechaHoraFinTrxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.chilexpress.cl/OSB/EBO/HeaderRequest")]
    public partial class datosConsumidor {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.chilexpress.cl/OSB/EBO/HeaderResponse")]
    [System.Xml.Serialization.XmlRootAttribute("headerResponse", Namespace="http://www.chilexpress.cl/DireccionesSSO/", IsNullable=false)]
    public partial class datosHeaderResponse : System.Web.Services.Protocols.SoapHeader {
        
        private datosTransaccion1 transaccionField;
        
        /// <remarks/>
        public datosTransaccion1 transaccion {
            get {
                return this.transaccionField;
            }
            set {
                this.transaccionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.chilexpress.cl/DireccionesSSO/")]
    public partial class ValidarDireccionRequest {
        
        private ValidarDireccionRequestType reqValidarDireccionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://ws.chilexpress.cl/OSB/INTERNO/IMP/ValidarDireccionReq")]
        public ValidarDireccionRequestType reqValidarDireccion {
            get {
                return this.reqValidarDireccionField;
            }
            set {
                this.reqValidarDireccionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.chilexpress.cl/DireccionesSSO/")]
    public partial class ValidarDireccionResponse {
        
        private ValidarDireccionResponseType respValidarDireccionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://ws.chilexpress.cl/OSB/INTERNO/IMP/ValidarDireccionResp")]
        public ValidarDireccionResponseType respValidarDireccion {
            get {
                return this.respValidarDireccionField;
            }
            set {
                this.respValidarDireccionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.chilexpress.cl/DireccionesSSO/")]
    public partial class ConsultarRegionesRequest {
        
        private ConsultarRegionesRequestType reqConsultarRegionesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://ws.chilexpress.cl/OSB/INTERNO/IMP/ConsultarRegionesReq")]
        public ConsultarRegionesRequestType reqConsultarRegiones {
            get {
                return this.reqConsultarRegionesField;
            }
            set {
                this.reqConsultarRegionesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.chilexpress.cl/DireccionesSSO/")]
    public partial class ConsultarRegionesResponse {
        
        private ConsultarRegionesResponseType respConsultarRegionesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://ws.chilexpress.cl/OSB/INTERNO/IMP/ConsultarRegionesResp")]
        public ConsultarRegionesResponseType respConsultarRegiones {
            get {
                return this.respConsultarRegionesField;
            }
            set {
                this.respConsultarRegionesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.chilexpress.cl/DireccionesSSO/")]
    public partial class ConsultarOficinasRequest {
        
        private ConsultarOficinasRequestType reqConsultarOficinasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://ws.chilexpress.cl/OSB/INTERNO/IMP/ConsultarOficinasReq")]
        public ConsultarOficinasRequestType reqConsultarOficinas {
            get {
                return this.reqConsultarOficinasField;
            }
            set {
                this.reqConsultarOficinasField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.chilexpress.cl/DireccionesSSO/")]
    public partial class ConsultarOficinasResponse {
        
        private ConsultarOficinasResponseType respConsultarOficinasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://ws.chilexpress.cl/OSB/INTERNO/IMP/ConsultarOficinasResp")]
        public ConsultarOficinasResponseType respConsultarOficinas {
            get {
                return this.respConsultarOficinasField;
            }
            set {
                this.respConsultarOficinasField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.chilexpress.cl/DireccionesSSO/")]
    public partial class ConsultarComunaCoberturaRequest {
        
        private ConsultarComunaCoberturaRequestType reqConsultarComunaCoberturaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://ws.chilexpress.cl/OSB/INTERNO/IMP/ConsultarComunaCoberturaReq")]
        public ConsultarComunaCoberturaRequestType reqConsultarComunaCobertura {
            get {
                return this.reqConsultarComunaCoberturaField;
            }
            set {
                this.reqConsultarComunaCoberturaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.chilexpress.cl/DireccionesSSO/")]
    public partial class ConsultarComunaCoberturaResponse {
        
        private ConsultarComunaCoberturaResponseType respConsultarComunaCoberturaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://ws.chilexpress.cl/OSB/INTERNO/IMP/ConsultarComunaCoberturaResp")]
        public ConsultarComunaCoberturaResponseType respConsultarComunaCobertura {
            get {
                return this.respConsultarComunaCoberturaField;
            }
            set {
                this.respConsultarComunaCoberturaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ValidarDireccionOpCompletedEventHandler(object sender, ValidarDireccionOpCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidarDireccionOpCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidarDireccionOpCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ValidarDireccionResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ValidarDireccionResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ConsultarRegionesOpCompletedEventHandler(object sender, ConsultarRegionesOpCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarRegionesOpCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarRegionesOpCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ConsultarRegionesResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ConsultarRegionesResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ConsultarOficinasOpCompletedEventHandler(object sender, ConsultarOficinasOpCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarOficinasOpCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarOficinasOpCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ConsultarOficinasResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ConsultarOficinasResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ConsultarComunaCoberturaOpCompletedEventHandler(object sender, ConsultarComunaCoberturaOpCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarComunaCoberturaOpCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarComunaCoberturaOpCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ConsultarComunaCoberturaResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ConsultarComunaCoberturaResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591